version: '2.1'
services:
  perry:
    image: cwds/perry:0.4.5-HF12
    hostname: perry
    ports:
      - ${PERRY_PORT}:8080
      - ${PERRY_ADMIN_PORT}:8092
    env_file: .env

  db2data:
    image: cwds/db2data
    hostname: db2data
    ports:
      - ${DB_CMS_DB2_PORT}:${DB_CMS_DB2_PORT}
    env_file: .env

  case-management-api:
    image: cwds/case-management-api
    hostname: case-management-api
    depends_on:
      db2data:
        condition: service_started
      perry:
        condition: service_started
    restart: on-failure
    ports:
      - ${CASE_MANAGEMENT_API_PORT}:8080
    env_file: .env