package gov.ca.cwds.cm.service.dto;

import com.fasterxml.jackson.databind.PropertyNamingStrategy;
import com.fasterxml.jackson.databind.annotation.JsonNaming;
import gov.ca.cwds.cm.RequestResponse;
import gov.ca.cwds.cm.service.mapper.tool.RemoveTrailingSpaces;
import io.dropwizard.validation.OneOf;
import io.swagger.annotations.ApiModelProperty;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.util.List;

/**
 * @author CWDS TPT-3 Team
 */

@Data
@EqualsAndHashCode(callSuper = false)
@Builder
@NoArgsConstructor
@AllArgsConstructor
@SuppressWarnings({"squid:S3437"})
@JsonNaming(PropertyNamingStrategy.SnakeCaseStrategy.class)
public class LandingDTO extends BaseDTO implements RequestResponse {

  private static final long serialVersionUID = 3787457561716324977L;

  @NotNull
  @Size(max = 10)
  @ApiModelProperty(
    value =
        "A system generated number used to uniquely identify each CASE_LOAD. This ID is composed of a base 62 "
            + "Creation Timestamp and the STAFF_PERSON ID (a sequential 3 digit base 62 number generated by the system). "
            + "This value eliminates the need for an additional set of Creation Timestamp and Creation User ID which is "
            + "needed to satisfy the Audit Trail requirement.",
    example = "0YIPkZU0S0"
  )
  private String id;

  @RemoveTrailingSpaces
  @ApiModelProperty(value = "Text that DESCRIBES_THE_WORK_OF a ASSIGNMENT_UNIT", example = "Emergency Response")
  private String unit;

  @RemoveTrailingSpaces
  @ApiModelProperty(value = "The user specified name or number that an ASSIGNMENT UNIT uses to identify a CASE LOAD", example = "ER3")
  private String caseload;

  @Size(max = 2)
  @ApiModelProperty(
    value =
        "A code, with values between '01' and '58' or '99' that indicates which county has primary assignment "
            + "responsibility for the CASE or REFERRAL that this row belongs to. The value for each county is "
            + "identical to the Logical ID value for the county in the Government_Entity_Type code table.",
    example = "10"
  )
  private String countySpecificCode;

  @NotNull
  @OneOf(
    value = {"Y", "N"},
    ignoreCase = true,
    ignoreWhitespace = true
  )
  @ApiModelProperty(
    value =
        "This Y/N indicates whether this CASE_LOAD is the designated In Box for routing and transferring of incoming "
            + "ASSIGNMENTs for this particular ASSIGNMENT_UNIT. There can only be one Assignment Desk (In Box) Case Load"
            + " per ASSIGNMENT_UNIT and it must also be created at the same time the unit is being created.",
    example = "N"
  )
  private String assignmentDeskCaseloadIndicator;

  @ApiModelProperty(value = "List of related cases/referrals/reminders.")
  private List<LandingItemDTO> items;

}
