package gov.ca.cwds.cm.service.dto;

import com.fasterxml.jackson.databind.PropertyNamingStrategy;
import com.fasterxml.jackson.databind.annotation.JsonNaming;
import gov.ca.cwds.cm.RequestResponse;
import gov.ca.cwds.cm.service.mapper.tool.RemoveTrailingSpaces;
import io.swagger.annotations.ApiModelProperty;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.util.List;

/**
 * @author CWDS TPT-3 Team
 */

@Data
@EqualsAndHashCode(callSuper = false)
@Builder
@NoArgsConstructor
@AllArgsConstructor
@SuppressWarnings({"squid:S3437"})
@JsonNaming(PropertyNamingStrategy.SnakeCaseStrategy.class)
public class LandingDTO extends BaseDTO implements RequestResponse {

  private static final long serialVersionUID = 3787457561716324977L;

  @NotNull
  @Size(max = 10)
  @ApiModelProperty(
    value =
        "A system generated number used to uniquely identify each CASE_LOAD. This ID is composed of a base 62 "
            + "Creation Timestamp and the STAFF_PERSON ID (a sequential 3 digit base 62 number generated by the system). "
            + "This value eliminates the need for an additional set of Creation Timestamp and Creation User ID which is "
            + "needed to satisfy the Audit Trail requirement.",
    example = "0YIPkZU0S0"
  )
  private String id;

  @RemoveTrailingSpaces
  @ApiModelProperty(value = "Text that DESCRIBES_THE_WORK_OF a ASSIGNMENT_UNIT", example = "Emergency Response")
  private String unit;

  @RemoveTrailingSpaces
  @ApiModelProperty(value = "The user specified name or number that an ASSIGNMENT UNIT uses to identify a CASE LOAD", example = "ER3")
  private String caseload;

  @ApiModelProperty(value = "List of cases/referrals.")
  private List<LandingItemDTO> items;

}
